### ISSUE TITLE
The scaleM Function

### ISSUE THREAD

**Issue by robustport** [msalibian/RobStatTM#11]
The second sentence of the Description for the scaleM is confusing with regard to the "sample standard deviation" part:  "M-estimators of scale are a robust alternative to the sample standard deviation."   I guess replacing scale by "dispersion" would make this sentence correct, but that is not what is needed here.  Maybe replace "sample standard deviation" with "square root of the sample second moment" ?

**Comment by msalibian** [comment]
The help documentation for `scaleM` is in the file DCML.R (lines 1-51).
