### ISSUE TITLE
Deprecated MLocDis and scalem

### ISSUE THREAD

**Issue by robustport** [msalibian/RobStatTM#12]
The man pages for the functions MLocDis and mscale should state in the Description that these functions are deprecated, and that MLocDis is replaced by locScaleM and mscale has been replaced by scaleM.

**Comment by dan9401** [comment]
Test omment.

**Comment by msalibian** [comment]
Both `MLocDis` and `mscale` are the same function as `locScaleM` and `scaleM`, respectively, and thus have the same help pages. If we want different text in their help pages, we might need to add them as separate functions. 

- Removing `MLocDis()` should be easy. I believe the original name was used either in the examples in the book, or in the scripts. We should check that they are not there anymore.  
- Removing `mscale()` would be more difficult, as it was originally meant as an internal function, and is used extensively throughout the package (see, e.g. search for "mscale(" on the search box at the top of this page)

**Comment by robustport** [comment]
Matias,  Thanks.  Actually, I was not thinking to remove them, just deprecate them, which in usual practice does not imply removing them.  That said, now that I see your explanation about scaleM, I already commented that I think it best to not delete mscale, and just keep for internal use, not available with the help function, but could be found with getAnywhere by anyone who knows about getAnywhere.

**Comment by robustport** [comment]
Thanks.  Doug
