### ISSUE TITLE
scaleM man page problems 

### ISSUE THREAD

**Issue by robustport** [msalibian/RobStatTM#14]
The following problems should be fixed in the scaleM man page:
1.  argument tuning.chi is called cc in the Details paragraph (we should be consistent)
2.  argument delta is called b in the Details paragraph (we should be consistent)
3.  the function name is scaleM but in the Example the deprecated name mscale is used

**Comment by msalibian** [comment]
#11

**Comment by msalibian** [comment]
Done.
