### ISSUE TITLE
locScaleM function uses mscale function

### ISSUE THREAD

**Issue by robustport** [msalibian/RobStatTM#15]
The locScaleM function uses the mscale function, which is in effect a deprecated function replaced by the function scaleM.  So the 4 instances of mscale in locScaleM should be replaced by scaleM.  The main point here is to avoid confusing users by using two different names of a function in different places.

This Issue no doubt occurs in other places, and we should clean this up for the next RobStatTM release.

**Comment by msalibian** [comment]
`mscale` was originally written as an internal function, and is not yet deprecated. It is used extensively throughout the package. Please see the second point in my answer to #12 .

**Comment by robustport** [comment]
Just to be clear, I am now aware that we should keep mscale "as is" as a hidden function and make scaleM work with way you suggested in response to one of the current Issues.

**Comment by msalibian** [comment]
Done.
