### ISSUE TITLE
ERROR: compilation failed for package ‘RobStatTM’

### ISSUE THREAD

**Issue by singha53-zz** [msalibian/RobStatTM#2]
devtools::install_github("msalibian/RobStatTM") not working... 

I installed the dependencies as you mentioned prior to installing.

**Comment by msalibian** [comment]
What error(s) do you get?

**Comment by singha53-zz** [comment]
seems like a complier issue:

[installing_RobStatTM_Rversion_3.5.1_2018-07-02_macOS_Sierra_10.12.6.txt](https://github.com/msalibian/RobStatTM/files/2696495/installing_RobStatTM_Rversion_3.5.1_2018-07-02_macOS_Sierra_10.12.6.txt)

https://stackoverflow.com/questions/47930557/cannot-install-xts-package-for-r-on-mac-os

Please let me know if you have thoughts on this. In the meantime, I'll keep debugging...

**Comment by msalibian** [comment]
Sorry I can't help you with that one, I don't have any experience with installing packages from source on Mac OS. However, the package has been submitted to CRAN, so I'm hopeful it'll be available there soon.

**Comment by msalibian** [comment]
The RobStatTM package is on CRAN now (has been for a few months), and I expect you should be able to install it directly from there.

**Comment by singha53-zz** [comment]
awesome. that worked!
Thanks!
