### ISSUE TITLE
lmrobdetMM returns 0 coefficients or fails

### ISSUE THREAD

**Issue by harrysouthworth** [msalibian/RobStatTM#5]
Running the following line repeatedly throws up varying results, or sometimes an error.

```
lmrobdetMM(mpg ~ wt + gear, data = mtcars)

Call:
lmrobdetMM(formula = mpg ~ wt + gear, data = mtcars)
Coefficients:
(Intercept)           wt         gear  
    38.6205      -5.4383      -0.2986 

lmrobdetMM(mpg ~ wt + gear, data = mtcars)

Call:
lmrobdetMM(formula = mpg ~ wt + gear, data = mtcars)
Coefficients:
(Intercept)           wt         gear  
          0            0            0  

lmrobdetMM(mpg ~ wt + gear, data = mtcars)
Error in lmrob.fit(X, y, control, init = S.init, mf = mf) : 
  init$scale >= 0 is not TRUE
```

I don't have any clues as to what goes wrong and am unlikely to find time to dig deeper today. I'll let you know if I figure anything out.

**Comment by msalibian** [comment]
Interesting. 

The fits with 0 coefficients seem to be due to the fact that the variable `gear` is constant for a large proportion of the data, which results in a perfect "vertical" fit (with infinite slope). 
```
pairs(mtcars[c(1, 6, 10)])
```
![vertical](https://user-images.githubusercontent.com/5422467/98387189-f444b180-2005-11eb-9504-1e4b84ead996.png)

This is, by definition, the optimal fit since the robust estimator of the residuals scale is then zero (which is the lowest value possible). 

Adding a bit of "noise" fixes the issue, as expected:
```
Call:
lmrobdetMM(formula = mpg ~ wt + I(jitter(gear, amount = 1/100)), data = mtcars)
Coefficients:
                    (Intercept)                               wt  I(jitter(gear, amount = 1/100))  
                        38.5773                          -5.4346                          -0.2903  
```
Having said this, however, this example still raises a couple of issues:
1. I would have expected the solution to always be the same (cue the `det` in `lmrobdetMM`);
2. The variable `gear` should probably taken as a factor. This does not resolve the "exact fit" issue, but highlights a well-known problem with M estimators--they cannot be used with "fixed design" problems if one category contains about half of the data (in the `lmrobdetMM` implementation, the proportion is `(n - p - 1)/(2n)`.

I will look at the problem 1 above, and follow up here.

**Comment by msalibian** [comment]
This seems to be a problem in pyinit::pyinit. Although the candidates for regression estimators are always the same (i.e. `lmrobdetMM` deserves the `det` part of its name after all), the residual scale estimator associated with the exact vertical fit is sometimes not zero, and can even be negative. I believe this is a bug in the pyinit::pyinit code. I will follow it up with the author of that package. 

Here's the script to reproduce this behaviour (you may need to run it many times to observe the different kind of outputs). The entry of interest is the 6th element of `a$objective` below, which should be essentially zero.

```
X <- model.matrix(mpg ~ wt + gear, data=mtcars)
y <- as.vector(mtcars$mpg)
control <- RobStatTM::lmrobdet.control()
n <- nrow(X)
p <- ncol(X)
dee <- control$bb
if(control$corr.b) dee <- dee * (1-(p/n))
( a <- pyinit::pyinit(x=X, y=y, intercept=FALSE, delta=dee,
                    cc=1.54764,
                    psc_keep=control$psc_keep*(1-(p/n)), resid_keep_method=control$resid_keep_method,
                    resid_keep_thresh = control$resid_keep_thresh, resid_keep_prop=control$resid_keep_prop,
                    maxit = control$py_maxit, eps=control$py_eps,
                    mscale_maxit = control$mscale_maxit, mscale_tol = control$mscale_tol,
                    mscale_rho_fun="bisquare") )
```
Some illustrative outputs:
1. This one is "good":
```
# $coefficients
# [,1]        [,2]      [,3]      [,4]      [,5] [,6]      [,7]
# [1,] 34.81987374 34.81987374 32.596750 58.213513 58.213513    0 48.566817
# [2,] -4.71378028 -4.71378028 -5.475169 -6.553094 -6.553094    0 -6.356656
# [3,] -0.01566553 -0.01566553  1.237416 -3.983916 -3.983916    0 -2.090457
# [,8]      [,9]      [,10]     [,11]
# [1,] 26.247175 44.411976 38.7776484 47.239577
# [2,] -4.660094 -5.249296 -6.4097299 -7.591443
# [3,]  2.378176 -1.857847  0.1296653 -1.270554
# 
# $objective
# [1] 3.169845 3.169845 3.433644 5.074703 5.074703 0.000000 3.475116 3.401738
# [9] 3.660265 3.227703 3.248764
```
2. This one reports a positive (~2.74) residual scale estimator for the "exact fit" candidate:
```
$coefficients
            [,1]        [,2]      [,3]      [,4]      [,5] [,6]      [,7]
[1,] 34.81987374 34.81987374 32.596750 58.213513 58.213513    0 48.566817
[2,] -4.71378028 -4.71378028 -5.475169 -6.553094 -6.553094    0 -6.356656
[3,] -0.01566553 -0.01566553  1.237416 -3.983916 -3.983916    0 -2.090457
          [,8]      [,9]      [,10]     [,11]
[1,] 26.247175 44.411976 38.7776484 47.239577
[2,] -4.660094 -5.249296 -6.4097299 -7.591443
[3,]  2.378176 -1.857847  0.1296653 -1.270554

$objective
 [1] 3.169845 3.169845 3.433644 5.074703 5.074703 2.746835 3.475116 3.401738
 [9] 3.660265 3.227703 3.248764
```
3. This one reports a negative residual scale estimator for the "exact fit" candidate:
```
# $coefficients
# [,1]        [,2]      [,3]      [,4]      [,5] [,6]      [,7]
# [1,] 34.81987374 34.81987374 32.596750 58.213513 58.213513    0 48.566817
# [2,] -4.71378028 -4.71378028 -5.475169 -6.553094 -6.553094    0 -6.356656
# [3,] -0.01566553 -0.01566553  1.237416 -3.983916 -3.983916    0 -2.090457
# [,8]      [,9]      [,10]     [,11]
# [1,] 26.247175 44.411976 38.7776484 47.239577
# [2,] -4.660094 -5.249296 -6.4097299 -7.591443
# [3,]  2.378176 -1.857847  0.1296653 -1.270554
# 
# $objective
# [1]   3.169845   3.169845   3.433644   5.074703   5.074703 -13.799952
# [7]   3.475116   3.401738   3.660265   3.227703   3.248764
```

**Comment by msalibian** [comment]
One more thing. Making `gear` to be a factor (as it may be appropriate here), and using the alternate SM initial estimator for models with categorical and continuous predictors (see Section 5.7.5 of [Robust Statistics: Theory and Methods (with R), 2nd Edition](http://www.wiley.com/go/maronna/robust) fixes the issue in this case:
```
lmrobdetMM(mpg ~ wt + as.factor(gear), data = mtcars, control=lmrobdet.control(initial='SM'))

Call:
lmrobdetMM(formula = mpg ~ wt + as.factor(gear), data = mtcars, control = lmrobdet.control(initial = "SM"))
Coefficients:
     (Intercept)                wt  as.factor(gear)4  as.factor(gear)5  
         35.2182           -4.9130            2.1396           -0.9043  
```

**Comment by harrysouthworth** [comment]
Thanks for your efforts with this. It's appreciated.

I discovered the problem whilst working with a dataset with about 1200
observations in it. The model allowed for a 4-level factor with approximate
numbers of observations at each level, and 2 continuous covariates. So I
don't think it's an edge-case thing. The gear example might be poor, but I
just wanted a reproducible example.

Thanks again,
Harry

**Comment by msalibian** [comment]
Thanks again for catching this issue. We tracked it down to a bug in the pyinit package (essentially, candidates resulting from singular LS fits were being returned with an uninitialized value for the corresponding residual scale estimate, hence the randomness in the results). These initial candidates are now being correctly ignored. 

The updated `pyinit` package might take a week or two to be available on CRAN, but meanwhile you can update both `pyinit` and `RobStatTM` from GitHub as usual:
```
devtools::install_github("dakep/pyinit")
devtools::install_github("msalibian/RobStatTM")
```
Note that if you haven't recently updated the package `remotes`, the above `install_github` calls may give an error which should be resolved once `remotes` is updated from CRAN.

**Comment by harrysouthworth** [comment]
Once more, thanks for all your efforts with this.
Harry
