### ISSUE TITLE
partial argument name matching in calls to seq

### ISSUE THREAD

**Issue by ethanbsmith** [msalibian/RobStatTM#8]
calls to `seq` are matching on parameter `length.out` to argument `length`

/R/psiFUnUtils.R

lines 117 and 134 call `seq(..., length = 100)` should be `seq(..., length.out = 100)`

**Comment by msalibian** [comment]
Thanks @ethanbsmith There are indeed many more instances of what you point out throughout the code. Luckily there is no ambiguity in the current calls to `seq` since there is no other argument that would match to `length`. I will fix the calls to `seq` appropriately in the next update.

**Comment by msalibian** [comment]
This is now fixed here on GH. Will go to CRAN with our next update. Thanks for your help catching this.

**Comment by ethanbsmith** [comment]
yep, def wasnt breaking anything, just hygiene .  i always run w/ these for my own sanity: 
```r
options(warnPartialMatchAttr = TRUE,
		warnPartialMatchDollar = TRUE,
		warnPartialMatchArgs = TRUE)
```
thx for the quick fix
